# 🔢 NumPy Array Operations — 10 Exercises
A hands-on walkthrough of core NumPy operations: array creation, manipulation, indexing, and aggregation.

---

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.2


---
## 🌟 Exercise 1 — Array Creation and Manipulation
**Task:** Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
arr1 = np.arange(10)
print("Result:")
print(repr(arr1))

Result:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


---
## 🌟 Exercise 2 — Type Conversion and Array Operations
**Task:** Convert the list `[3.14, 2.17, 0, 1, 2]` into a NumPy array and cast its dtype to integer.

In [3]:
float_list = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(float_list).astype(int)
print("Original list:   ", float_list)
print("NumPy int array: ", repr(arr2))

Original list:    [3.14, 2.17, 0, 1, 2]
NumPy int array:  array([3, 2, 0, 1, 2])


---
## 🌟 Exercise 3 — Working with Multi-Dimensional Arrays
**Task:** Create a 3×3 NumPy array with values from 1 to 9.

In [4]:
arr3 = np.arange(1, 10).reshape(3, 3)
print("3×3 array:")
print(repr(arr3))

3×3 array:
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


---
## 🌟 Exercise 4 — Creating a Multi-Dimensional Array with Random Numbers
**Task:** Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [5]:
np.random.seed(0)                          # seed for reproducibility
arr4 = np.round(np.random.random((4, 5)), 2)
print("Random (4×5) array:")
print(repr(arr4))

Random (4×5) array:
array([[0.55, 0.72, 0.6 , 0.54, 0.42],
       [0.65, 0.44, 0.89, 0.96, 0.38],
       [0.79, 0.53, 0.57, 0.93, 0.07],
       [0.09, 0.02, 0.83, 0.78, 0.87]])


---
## 🌟 Exercise 5 — Indexing Arrays
**Task:** Select the **second row** (index 1) from the given 2D array.

In [6]:
arr5 = np.array([[21, 22, 23, 22, 22],
                 [20, 21, 22, 23, 24],
                 [21, 22, 23, 22, 22]])

second_row = arr5[1]
print("Full array:")
print(repr(arr5))
print("\nSecond row (index 1):")
print(repr(second_row))

Full array:
array([[21, 22, 23, 22, 22],
       [20, 21, 22, 23, 24],
       [21, 22, 23, 22, 22]])

Second row (index 1):
array([20, 21, 22, 23, 24])


---
## 🌟 Exercise 6 — Reversing Elements
**Task:** Reverse the order of elements in a 1D array (first element becomes last).

In [7]:
arr6 = np.arange(10)
reversed_arr = arr6[::-1]
print("Original: ", repr(arr6))
print("Reversed: ", repr(reversed_arr))

Original:  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Reversed:  array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


---
## 🌟 Exercise 7 — Identity Matrix
**Task:** Create a 4×4 identity matrix using NumPy.

In [8]:
identity = np.eye(4)
print("4×4 Identity Matrix:")
print(repr(identity))

4×4 Identity Matrix:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


---
## 🌟 Exercise 8 — Simple Aggregate Functions
**Task:** Find the **sum** and **average** of a 1D array `[0..9]`.

In [9]:
arr8 = np.arange(10)
total   = arr8.sum()
average = arr8.mean()
print(f"Array:   {arr8}")
print(f"Sum:     {total}")
print(f"Average: {average}")

Array:   [0 1 2 3 4 5 6 7 8 9]
Sum:     45
Average: 4.5


---
## 🌟 Exercise 9 — Create Array and Change Its Structure
**Task:** Create a NumPy array with elements from 1 to 20, then reshape it into a 4×5 matrix.

In [10]:
arr9 = np.arange(1, 21).reshape(4, 5)
print("Reshaped 4×5 matrix:")
print(repr(arr9))

Reshaped 4×5 matrix:
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


---
## 🌟 Exercise 10 — Conditional Selection of Values
**Task:** Extract all **odd numbers** from a given NumPy array.

In [11]:
arr10 = np.arange(1, 11)
odd_numbers = arr10[arr10 % 2 != 0]
print("Original array: ", repr(arr10))
print("Odd numbers:    ", repr(odd_numbers))

Original array:  array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Odd numbers:     array([1, 3, 5, 7, 9])
